### ISSUE TITLE
Crash when adding packs and `package.yml` is missing enforce_dependencies

### ISSUE THREAD

**Issue by bschrag620** [rubyatscale/parse_packwerk#32]
A crash can happen when trying to use `packs` to create a new package and the package.yml is missing the `enforce_dependencies` setting. I'm only opening it as a possible issue because `packwerk validate` doesn't flag the `package.yml` as invalid. It feels like there should be a consistent experience here between `validate` and how `parse_packwerk` is building a new `ParsePackwerk::Package`.

The error is specifically raised by sorbet on line 27 in `/lib/parse_packwerk/package.rb`. If the yml file does not have `enforce_dependencies` then `const :enforce_dependencies` is in violation of the type since it doesn't permit `nil`.

I'm happy to open a fix for the issue by either providing a default value of `false` to the `const` definition or perhaps handling the missing `enforce_dependencies` entry with some more useful messaging to the end user so they are aware where the exact issue is. A third option would be for `parse_packwerk` to inject a new validator that requires `enforce_dependencies` be present.

In the end, this is a fairly small edge case that will only impact teams adding `packs` into an already existing code base that has existing `package.yml` files that may not conform to the expected values.

**Comment by schoblaska** [comment]
Hey @bschrag620 - now that https://github.com/rubyatscale/parse_packwerk/pull/34 is merged, can you confirm that this issue is resolved? Thanks!

**Comment by bschrag620** [comment]
Yes, thanks!
