### ISSUE TITLE
ParsePackwerk::Package#violations contracted changed to allow nil

### ISSUE THREAD

**Issue by technicalpickles** [rubyatscale/parse_packwerk#33]
Previously, this would return an Array, but now it can return possibly return nil. This was introduced in https://github.com/rubyatscale/parse_packwerk/pull/30

Our app is using this to build up a list of violations across different packs, and I saw that `violations` started being nilable. I'm not sure if this is an intended or accidental change to the API. I could go either way with which is better: having nil violations when there's (for example) not a TODO, versus an empty one, but I figure I flag it in case anyone notices/hits it!

**Comment by alexevanczuk** [comment]
Yeah – I think this should definitely default to an empty list!!
