### ISSUE TITLE
Bug: Fails to parse empty package.yml files

### ISSUE THREAD

**Issue by exterm** [rubyatscale/parse_packwerk#41]
https://github.com/rubyatscale/parse_packwerk/blob/cdf036af3a79b5c98feceb48666312aca865de70/lib/parse_packwerk/package.rb#L20

An empty `package.yml` file is perfectly valid for `packwerk`. It declares a folder as a package and does nothing else. `parse_packwerk` should not raise in this case.

**Comment by schoblaska** [comment]
Agreed. Thanks for the issue! I have a PR up here that removes this check: https://github.com/rubyatscale/parse_packwerk/pull/42
