### ISSUE TITLE
ParsePackwerk.package_from_path should return a non-nil able Package

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/parse_packwerk#8]
https://github.com/rubyatscale/parse_packwerk/blob/a542956c62845cf6e6addd5efbfd3fc0e744ed7b/lib/parse_packwerk.rb#L42

This should always return root if another package cannot be found.

**Comment by professor** [comment]
Sovled by https://github.com/rubyatscale/parse_packwerk/pull/10
