### ISSUE TITLE
ParsePackwerk.all should work more like Packwerk::PackageSet

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/parse_packwerk#9]
https://github.com/Shopify/packwerk/blob/main/lib/packwerk/package_set.rb

This would make the cache simpler -- the user calls `ParsePackwerk.load_all` and gets a `PackageSet`. This is cached. They can recall `ParsePackwerk.load_all` to get an uncached package set. ParsePackwerk.all can then be deprecated in favor of this simpler alternative later.

**Comment by professor** [comment]
load_all no longer exists, closing this issue.
